### ISSUE TITLE
Resources not working

### ISSUE THREAD

**Issue by twdkeule** [gerbera/gerbera#1165]
Hi,

I have added a resources section to the configuration to add fanart and subtitles:
```
  <import>
    [...]
    <resources>
      <subtitle>
        <add-file name="%filename%.srt"/>
        <add-file name="%filename%.en.srt"/>
        <add-file name="%filename%.nl.srt"/>
      </subtitle>
      <fanart>
        <add-file name="%filename%-thumb.jpg"/>
        <add-file name="poster.jpg"/>
      </fanart>
      <container>
        <add-file name="poster.jpg"/>
      </container>
      <resource>
        <add-file name="%filename%.srt"/>
        <add-file name="%filename%.en.srt"/>
        <add-file name="%filename%.nl.srt"/>
        <add-file name="%filename%-thumb.jpg"/>
        <add-file name="poster.jpg"/>
      </resource>
    </resources>
  </import>
```

However, when testing with VLC, subtitles don't seem to be loaded.
Fanart works for the movie items themselves, but not for containers.

Loggin:

Fanart found:
```
Jan 28 09:32:58 acer-laptop gerbera[101111]: 2021-01-28 09:32:58  debug: [fanart_handler.cc:56] getFanArtPath(): Folder name: /.../film/Aladdin (2019)
Jan 28 09:32:58 acer-laptop gerbera[101111]: 2021-01-28 09:32:58  debug: [fanart_handler.cc:63] getFanArtPath(): folder.jpg: missing
Jan 28 09:32:58 acer-laptop gerbera[101111]: 2021-01-28 09:32:58  debug: [fanart_handler.cc:63] getFanArtPath(): poster.jpg: found
Jan 28 09:32:58 acer-laptop gerbera[101111]: 2021-01-28 09:32:58  debug: [fanart_handler.cc:87] serveContent(): FanArt: Opening name: /.../film/Aladdin (2019)/poster.jpg
```

Subtitles not found:
```
Jan 28 09:33:03 acer-laptop gerbera[101111]: 2021-01-28 09:33:03  debug: [server.cc:485] createRequestHandler(): Filename: /content/media/object_id/10187/res_id/0/ext/file.srt
Jan 28 09:33:03 acer-laptop gerbera[101111]: 2021-01-28 09:33:03  debug: [file_request_handler.cc:69] getInfo(): start
Jan 28 09:33:03 acer-laptop gerbera[101111]: 2021-01-28 09:33:03  debug: [upnp_clients.cc:218] getInfo(): client info: 192.168.1.191:62534 'VLC/3.0.12 LibVLC/3.0.12' -> 'Unknown' as None
Jan 28 09:33:03 acer-laptop gerbera[101111]: 2021-01-28 09:33:03  debug: [file_request_handler.cc:85] getInfo(): full url (filename): /content/media/object_id/10187/res_id/0/ext/file.srt, parameters: object_id/10187/res_id/0/ext/file.srt
Jan 28 09:33:03 acer-laptop gerbera[101111]: 2021-01-28 09:33:03 warning: [server.cc:533] operator()(): Subtitle file /.../film/Aladdin (2019)/Aladdin (2019) - Bluray-2160p HDR x265 AC3.srt is not available.
```

Folder content:
```
/.../film/Aladdin\ \(2019\)/
total 15G
-rwxrwxrwx 1 root root 133K Jun 27  2020 'Aladdin (2019) - Bluray-2160p HDR x265 AC3.en.srt'
-rwxrwxrwx 2 root root  15G Jun 27  2020 'Aladdin (2019) - Bluray-2160p HDR x265 AC3.mkv'
-rwxrwxrwx 1 root root 7.0K Jan 24 10:40 'Aladdin (2019) - Bluray-2160p HDR x265 AC3.nfo'
-rwxrwxrwx 1 root root 1.7M Jun 26  2020  fanart.jpg
-rwxrwxrwx 1 root root 1.2M Jun 26  2020  poster.jpg
```

I am running Gerbera 1.6.0 from the Ubuntu PPA.

**Comment by whyman** [comment]
Hey there have been a decent amount of changes in the code in that area since 1.6.

Can you try a git build and see if it helps at all?

You can try the new deb repo (feedback welcome!)
```bash
curl -fsSL https://gerbera.io/gpg | sudo apt-key add -
sudo apt-add-repository https://dl.bintray.com/gerbera/gerbera-git
```

Or grab a deb from a recent CI build: https://github.com/gerbera/gerbera/actions/runs/517343266

**Comment by KarlStraussberger** [comment]
> I am running Gerbera 1.6.0 from the Ubuntu PPA.

Especially, `resources `configuration was added after 1.6.0. So it won't work!

**Comment by twdkeule** [comment]
I have tried the latest CI build, but alas:
```
[27403.971350] gerbera[125327]: segfault at 40 ip 0000562fa60cd526 sp 00007f1b337fc100 error 4 in gerbera[562fa5ff7000+274000]
[27403.971365] Code: d0 48 8d 3d 6a e9 19 00 e8 b7 c9 f2 ff 0f 1f 80 00 00 00 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 4c 8d 67 08 55 53 48 83 ec 18 <4c> 8b 7f 10 4c 89 64 24 08 4d 85 ff 0f 84 bb 00 00 00 4c 8b 76 08
[27421.576873] gerbera[125513]: segfault at 40 ip 0000560a82052526 sp 00007ff2917f8100 error 4 in gerbera[560a81f7c000+274000]
[27421.576889] Code: d0 48 8d 3d 6a e9 19 00 e8 b7 c9 f2 ff 0f 1f 80 00 00 00 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 4c 8d 67 08 55 53 48 83 ec 18 <4c> 8b 7f 10 4c 89 64 24 08 4d 85 ff 0f 84 bb 00 00 00 4c 8b 76 08
```

Is there an easy way to get release 1.6.4  without building from soucre?
I cannot find it in https://github.com/gerbera/gerbera/actions?query=workflow%3Abuild-deb or in the bintray releases.

**Comment by KarlStraussberger** [comment]
Can you try starting from console with `--debug` enabled that you get loads of debug messages telling us where it crashes?

**Comment by twdkeule** [comment]
It seems the `--debug` option doesn't work

```
~ > sudo -u gerbera /usr/bin/gerbera -c /etc/gerbera/config.xml --debug
2021-01-28 13:07:05   info: [main.cc:74] logCopyright(): Gerbera UPnP Server v1.6.4-149-g0529ead1 - http://gerbera.io/
2021-01-28 13:07:05   info: [main.cc:75] logCopyright(): Copyright 2016-2021 Gerbera Contributors.
2021-01-28 13:07:05   info: [main.cc:76] logCopyright(): Gerbera is free software, covered by the GNU General Public License version 2
2021-01-28 13:07:05   info: [config_manager.cc:859] load(): Loading configuration from: /etc/gerbera/config.xml
2021-01-28 13:07:05   info: [config_manager.cc:865] load(): Checking configuration...
2021-01-28 13:07:05   info: [config_manager.cc:1277] load(): Configuration check succeeded.
2021-01-28 13:07:05   info: [sql_database.cc:2204] doMetadataMigration(): About to migrate metadata from mt_cds_object to mt_metadata
2021-01-28 13:07:05   info: [sql_database.cc:2205] doMetadataMigration(): No data will be removed from mt_cds_object
2021-01-28 13:07:05   info: [sql_database.cc:2221] doMetadataMigration(): Migrated metadata - object count: 0
2021-01-28 13:07:05   info: [config_manager.cc:1296] updateConfigFromDatabase(): Loading 0 configuration items from database
2021-01-28 13:07:05   info: [sql_database.cc:1784] _fillAutoscanDirectory(): Loading autoscan location: /mnt/Seagate/Seagate/series; recursive: true, last_modified: unset
2021-01-28 13:07:05   info: [sql_database.cc:1784] _fillAutoscanDirectory(): Loading autoscan location: /mnt/Seagate/Seagate/film; recursive: true, last_modified: unset
2021-01-28 13:07:05   info: [server.cc:107] run(): Initialising libupnp with interface: '', port: 49152
2021-01-28 13:07:05   info: [server.cc:119] run(): Initialized port: 49152
2021-01-28 13:07:05   info: [server.cc:125] run(): Server bound to: 192.168.1.3
2021-01-28 13:07:05   info: [server.cc:221] run(): The Web UI can be reached by following this link: http://192.168.1.3:49152/
fish: 'sudo -u gerbera /usr/bin/gerber…' terminated by signal SIGSEGV (Address boundary error)
~ [SIGSEGV]>
```

**Comment by twdkeule** [comment]
The crash happens after some of time (+- 1 minute) and doesn't seem to be related to user actions (I tried with and without loading the website and/or serving video to VLC).

Also, with this build no fanart is displayed any more. Or do I need to remove and re-import the library for that?

**Comment by KarlStraussberger** [comment]
Looks like your version is build without debugging capability (`gerbera --compile-info` look for `WITH_DEBUG`).

To get all the new features for fanarts, containers and thumbnails it's recommended to remove the database (incl. backup).

I suppose the crash happens when reading metadata from a particular file. You may try to reduce the autoscan to fewer files, but that's tedious.

It would be very helpful, if you compiled gerbera from source so we can find the reason for your crash before releasing 1.7

**Comment by whyman** [comment]
I think we can build the deb files in release mode but with symbols as a separate package, would be useful for such cases.

**Comment by twdkeule** [comment]
I tried building from source, but cmake is not cooperating.
I built libupnp 1.14.0 from source, but still:
```
> cmake .. -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1
[...]
-- Found pupnp: /usr/local/lib/libupnp.so (found suitable version "1.14.0", minimum required is "1.12.1")
CMake Error at cmake/Findpupnp.cmake:50 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:337 (find_package)
```

Also, I did **not** specify `-DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_LASTFM=1`, but cmake still required me to install libmatroska, libtag, libebml and others

**Comment by KarlStraussberger** [comment]
taglib and matroska are enabled by default, so you have to call `cmake` with `-DWITH_TAGLIB=0 -DWITH_MATROSKA=0`

Remove `CMakeCache.txt` and `CMakeFiles` from your build directory before running `cmake` again.

**Comment by twdkeule** [comment]
Success!
I started the new build, without deleting the old database and it crashed like before:
[gerbera_crash.txt](https://github.com/gerbera/gerbera/files/5892885/gerbera_crash.txt)

After that, I deleted the content of `/var/lib/gerbera/.config/gerbera` and restarted. Now it doesn't crash while it is importing the library. However importing is very slow:
[gerbera_import_slow.txt](https://github.com/gerbera/gerbera/files/5892900/gerbera_import_slow.txt)

**Comment by KarlStraussberger** [comment]
It's a bit of educated guessing because you did not capture a stacktrace (you need to run gerbera in gdb for that), but it seems that the access to the fanart picture in your mkv file crashed. If you're still in reach of the broken database, you may rerun the test with the following changes:

`src/file_request_handler.cc`:
```
@@ -159,6 +159,8 @@ void FileRequestHandler::getInfo(const char* filename, UpnpFileInfo* info)
-        // get size
-        io_handler->open(UPNP_READ);
-        io_handler->seek(0L, SEEK_END);
-        off_t size = io_handler->tell();
-        io_handler->close();
-
-        UpnpFileInfo_set_FileLength(info, size);
+        if (io_handler.get() != nullptr) {
+            // get size
+            io_handler->open(UPNP_READ);
+            io_handler->seek(0L, SEEK_END);
+            off_t size = io_handler->tell();
+            io_handler->close();
+            UpnpFileInfo_set_FileLength(info, size);
+        }
```

Producing debug output is slowing down the import process extremely!

**Comment by twdkeule** [comment]
I recreated it with 1.6.0 and then running the built binary.
```
Reading symbols from ./gerbera...
(gdb) run
Starting program: /home/thomas/gerbera -c /etc/gerbera/config.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2021-01-29 14:09:42   info: Gerbera UPnP Server v1.6.4-160-ge0bc8757 - http://gerbera.io/
2021-01-29 14:09:42   info: Copyright 2016-2021 Gerbera Contributors.
2021-01-29 14:09:42   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-01-29 14:09:42   info: Loading configuration from: /etc/gerbera/config.xml
2021-01-29 14:09:42   info: Checking configuration...
2021-01-29 14:09:42   info: Configuration check succeeded.
2021-01-29 14:09:42   info: Running an automatic database upgrade from database version 5 to version 6...
2021-01-29 14:09:42   info: Database upgrade successful.
2021-01-29 14:09:42   info: Running an automatic database upgrade from database version 6 to version 7...
2021-01-29 14:09:42   info: Database upgrade successful.
2021-01-29 14:09:42   info: About to migrate metadata from mt_cds_object to mt_metadata
2021-01-29 14:09:42   info: No data will be removed from mt_cds_object
2021-01-29 14:09:42   info: Migrated metadata - object count: 0
2021-01-29 14:09:42   info: Loading 0 configuration items from database
2021-01-29 14:09:42   info: Initialising libupnp with interface: '', port: 49152
2021-01-29 14:09:42   info: Initialized port: 49152
2021-01-29 14:09:42   info: Server bound to: 192.168.1.3
2021-01-29 14:09:43   info: The Web UI can be reached by following this link: http://192.168.1.3:49152/
[...]
Thread 10 "gerbera" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed7fa700 (LWP 588957)]
0x0000555555641546 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_begin (this=0x30) at /usr/include/c++/9/bits/stl_tree.h:751
751               (this->_M_impl._M_header._M_parent);
(gdb) bt
#0  0x0000555555641546 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_begin (this=0x30) at /usr/include/c++/9/bits/stl_tree.h:751
#1  0x0000555555637f55 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::find (this=0x30, __k="FanArt") at /usr/include/c++/9/bits/stl_tree.h:2570
#2  0x000055555562ac2b in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::find (this=0x30, __x="FanArt") at /usr/include/c++/9/bits/stl_map.h:1194
#3  0x00005555556ac0b6 in DirectoryTweak::hasFanArtFile (this=0x0) at /home/.../programming/gerbera/src/config/directory_tweak.h:133
#4  0x0000555555738b1d in FanArtHandler::serveContent (this=0x7ffff0058eb0, item=std::shared_ptr<CdsObject> (use count 3, weak count 0) = {...}, resNum=1) at /home/.../programming/gerbera/src/metadata/metacontent_handler.cc:149
#5  0x00005555557ef661 in FileRequestHandler::getInfo (this=0x7fffdc019ef0, filename=0x7ffff0044120 "/content/media/object_id/27/res_id/1/rct/aa", info=0x7fffdc0073e0) at /home/.../programming/gerbera/src/file_request_handler.cc:158
#6  0x0000555555749010 in Server::<lambda(char const*, UpnpFileInfo*, void const*, void const**)>::operator()(const char *, UpnpFileInfo *, const void *, const void **) const (__closure=0x0, filename=0x7fffdc00a9b0 "/content/media/object_id/27/res_id/1/rct/aa", info=0x7fffdc0073e0, cookie=0x555555a80050, requestCookie=0x7fffed7f94b0)
    at /home/.../programming/gerbera/src/server.cc:510
#7  0x00005555557492d8 in Server::<lambda(char const*, UpnpFileInfo*, void const*, void const**)>::_FUN(const char *, UpnpFileInfo *, const void *, const void **) () at /home/.../programming/gerbera/src/server.cc:521
#8  0x00007ffff7f950a2 in ?? () from /lib/x86_64-linux-gnu/libupnp.so.17
#9  0x00007ffff7f8d91c in ?? () from /lib/x86_64-linux-gnu/libupnp.so.17
#10 0x00007ffff7f86bdf in ?? () from /lib/x86_64-linux-gnu/libupnp.so.17
#11 0x00007ffff7eac609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#12 0x00007ffff7182293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

The culprit is `src/metadata/metacontent_handler.cc:149`. 
`tweak == nullptr && !tweak->hasFanArtFile()` should be `tweak == nullptr || !tweak->hasFanArtFile()`
