### ISSUE TITLE
Crash in ffmpeg date metadata field parser

### ISSUE THREAD

**Issue by peterurbanec** [gerbera/gerbera#1209]
I have an mp3 file that has a `recorded_date` tag with a value `YYYY`. When scanning (with ffmpeg enabled), this causes a crash because `std::stoi()` throws an `invalid_argument` exception.

Here is the backtrace:
```
(gdb) where
#0  0xb7fd1549 in __kernel_vsyscall ()
#1  0xb7062e76 in raise () from /lib/libc.so.6
#2  0xb704b305 in abort () from /lib/libc.so.6
#3  0xb7294a00 in ?? () from /usr/lib/gcc/i686-pc-linux-gnu/10.2.0/libstdc++.so.6
#4  0xb72c38f4 in ?? () from /usr/lib/gcc/i686-pc-linux-gnu/10.2.0/libstdc++.so.6
#5  0xb72c396d in std::terminate() () from /usr/lib/gcc/i686-pc-linux-gnu/10.2.0/libstdc++.so.6
#6  0xb72c3c6b in __cxa_throw () from /usr/lib/gcc/i686-pc-linux-gnu/10.2.0/libstdc++.so.6
#7  0xb7297a87 in std::__throw_invalid_argument(char const*) () from /usr/lib/gcc/i686-pc-linux-gnu/10.2.0/libstdc++.so.6
#8  0x0057d39f in __gnu_cxx::__stoa<long, int, char, int> (__idx=0x0, __str=0xb4487ec0 "YYYY", __name=0x5f8bda "stoi", __convf=<optimized out>) at /usr/lib/gcc/i686-pc-linux-gnu/10.2.0/include/g++-v10/ext/string_conversions.h:83
#9  std::__cxx11::stoi (__base=10, __idx=0x0, __str=<error: Cannot access memory at address 0x706e7075>) at /usr/lib/gcc/i686-pc-linux-gnu/10.2.0/include/g++-v10/bits/basic_string.h:6547
#10 FfmpegHandler::addFfmpegMetadataFields (this=0xaaa79ac0, item=std::shared_ptr<CdsItem> (use count 3, weak count 0) = {...}, pFormatCtx=0xb446f960) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/metadata/ffmpeg_handler.cc:127
#11 0x0057d539 in FfmpegHandler::fillMetadata (this=0xaaa79ac0, item=std::shared_ptr<CdsItem> (use count 3, weak count 0) = {...}) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/metadata/ffmpeg_handler.cc:258
#12 0x004ecdd4 in MetadataHandler::setMetadata (config=std::shared_ptr<Config> (use count 11, weak count 0) = {...}, item=std::shared_ptr<CdsItem> (use count 3, weak count 0) = {...})
    at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/metadata/metadata_handler.cc:152
#13 0x004d6a07 in ContentManager::createObjectFromFile (this=0x6b7d0c, path=filesystem::path "/exported/Music/Paul Oakenfold/Misc/Paul Oakenfold [Tranceport] [03] Rendezvous- (Quadrophonic mix, featuring Tilt V. Paul Van Dyk).mp3" = {...}, magic=true, allow_fifo=false)
    at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:1133
#14 0x004d7190 in ContentManager::createSingleItem (this=0x6b7d0c, path=filesystem::path "/exported/Music/Paul Oakenfold/Misc/Paul Oakenfold [Tranceport] [03] Rendezvous- (Quadrophonic mix, featuring Tilt V. Paul Van Dyk).mp3" = {...}, 
    rootPath=filesystem::path "/exported/Music" = {...}, checkStorage=true, processExisting=false, task=std::shared_ptr<CMAddFileTask> (empty) = {...}) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:454
#15 0x004d864c in ContentManager::_addFile (this=0x6b7d0c, path=filesystem::path "/exported/Music/Paul Oakenfold/Misc/Paul Oakenfold [Tranceport] [03] Rendezvous- (Quadrophonic mix, featuring Tilt V. Paul Van Dyk).mp3" = {...}, 
    rootPath=filesystem::path "/exported/Music" = {...}, recursive=false, hidden=false, rescanResource=false, task=std::shared_ptr<CMAddFileTask> (empty) = {...}) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:506
#16 0x004d7fb1 in ContentManager::addFileInternal (this=0x6b7d0c, path=filesystem::path "/exported/Music/Paul Oakenfold/Misc/Paul Oakenfold [Tranceport] [03] Rendezvous- (Quadrophonic mix, featuring Tilt V. Paul Van Dyk).mp3" = {...}, 
    rootpath=filesystem::path "/exported/Music" = {...}, recursive=<optimized out>, async=false, hidden=<optimized out>, rescanResource=<optimized out>, lowPriority=false, parentTaskID=0, cancellable=<optimized out>)
    at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:1320
#17 0x004daf3e in ContentManager::_rescanDirectory (this=<optimized out>, adir=..., containerID=<optimized out>, task=...) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:726
#18 0x004db437 in CMRescanDirectoryTask::run (this=0xb44f28ac) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:1771
#19 0x004d4013 in ContentManager::threadProc (this=<optimized out>) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:1260
#20 0x004d4568 in ContentManager::staticThreadProc (arg=0x6b7d0c) at /usr/src/debug/net-misc/gerbera-1.6.1-r1/gerbera-1.6.1/src/content_manager.cc:1279
#21 0xb7eee05f in start_thread () from /lib/libpthread.so.0
#22 0xb7134906 in clone () from /lib/libc.so.6
```

My suggestion for a fix is to wrap the attempt at parsing the `date` field in a try/catch block and catch the possible exception that `std::stoi` can throw.

**Comment by KarlStraussberger** [comment]
Thanks for reporting the issue. It's in 1.6.1 and is already fixed in current head (pre 1.7.0)

**Comment by whyman** [comment]
Reported in #994 and fixed in #997.

**Comment by whyman** [comment]
Thanks for reporting!

**Comment by peterurbanec** [comment]
@whyman - Thanks for updating the Gentoo ebuild to 1.6.4. When I reported the bug I did not realise that the version in Gentoo was not the most recent release of Gerbera.

Can I suggest that updating Gentoo ebuilds is part of the Gerbera release process, as you appear to have the means? Thanks.
