### ISSUE TITLE
Problem with autoscan configuration - topcrash with inotify compiled but disabled

### ISSUE THREAD

**Issue by whorfin** [gerbera/gerbera#1275]
If Gerbera 1.7.0 is built with `-DWITH_INOTIFY=1` such that `HAVE_INOTIFY` is set
And if the used `config.xml` file only contains autoscan entries with use-inotify disabled, ie
` <autoscan use-inotify="no">`
Then gerbera crashes on start in
 ```
    auto config_inotify_list = getAutoscanListOption(CFG_IMPORT_AUTOSCAN_INOTIFY_LIST);
```
in `src/config/config_manager.cc`
Stack shows it blew off into trying to execute at 0x00000 which is seldom a good idea:
```
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x0000000001b51afa in ConfigManager::getAutoscanListOption (this=0x2559c60,
    option=CFG_IMPORT_AUTOSCAN_INOTIFY_LIST)
    at /home/whorfin/gerbera/gerbera-1.7.0/src/config/config_manager.cc:1433
No locals.
#2  0x0000000001b4ffd8 in ConfigManager::load (this=0x2559c60, userHome=...)
    at /home/whorfin/gerbera/gerbera-1.7.0/src/config/config_manager.cc:1293
        temp = {static npos = 18446744073709551615,
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2550a10 "none"}, _M_string_length = 4, {
            _M_local_buf = ")\000\000\000\000\000\000\000`\006\000\000\000\000\000",
            _M_allocated_capacity = 41}}
        tmpEl = {_root = 0x0}
        args = {_M_t = {
            _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<No data fields>}, <No data fields>}, <std::_Rb_tree_key_compare<std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
                _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}}, <std::_Rb_tree_header> = {_M_header = {
                  _M_color = std::_S_red, _M_parent = 0x0, _M_left = 0xfffffc7fffdf3808,
                  _M_right = 0xfffffc7fffdf3808}, _M_node_count = 0}, <No data fields>}}}
        self = {<std::__shared_ptr<Config, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<Config, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x2559c60,
            _M_refcount = {_M_pi = 0x2559c50}}, <No data fields>}
        co = {<std::__shared_ptr<ConfigSetup, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<ConfigSetup, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x2549260,
            _M_refcount = {_M_pi = 0x2549250}}, <No data fields>}
        __FUNCTION__ = "load"
        result = {status = pugi::status_ok, offset = 0, encoding = pugi::encoding_utf8}
        root = {_root = 0x256c038}
        version = {static npos = 18446744073709551615,
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xfffffc7fffdf37a0 "2"}, _M_string_length = 1, {
            _M_local_buf = "2\000\337\377\177\374\377\377\356\220;\357", <incomplete sequence \374\377\377>, _M_allocated_capacity = 18446740225416691762}}
        __func__ = "load"
        mysql_en = false
        sqlite3_en = true
        dbDriver = {static npos = 18446744073709551615,
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xfffffc7fffdf3780 "sqlite3"}, _M_string_length = 7, {
            _M_local_buf = "sqlite3\000\060\000\305\356", <incomplete sequence \374\377\377>,
            _M_allocated_capacity = 14466774471569779}}
        def_ipp = 25
        menu_opts = {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, [etc]
```
Changing the `use-inotify` to "yes" prevents the crash, even if there are no `mode="inotify"` entires, ie even if it is all timed mode, the crash doesn't happen.  But it sure does if use-inotify is disabled in the autoscan config.

**Comment by KarlStraussberger** [comment]
Nice finding!

**Comment by whyman** [comment]
I guess we should do a 1.7.1? @KarlStraussberger thoughts?

**Comment by KarlStraussberger** [comment]
It's not that critical. There is a workaround that is no hack. I think, we should wait for a solution to the import speed issue.
