### ISSUE TITLE
Remaining memory leaks

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#2289]
https://gist.github.com/neheb/10cfc490b163bbee492231ba682cce7d

from a quick glance, these don't seem to be easily fixable. Not quite sure.

**Comment by KarlStraussberger** [comment]
From my point of view, most of them are buffers that are acquired during startup and never freed because the "author" leaves this to happen on exit.

If we really observe a (slight) increase in memory during usage that's going to be critical in the long run.

**Comment by neheb** [comment]
well they are sorted by amount leaked :).

**Comment by neheb** [comment]
strange thing is, my raw branch now does not show any more leaks except for the ixml one. Although that's an internal libupnp one.

**Comment by KarlStraussberger** [comment]
There may be some static buffer that's allocated once and never freed - because it's freed on exit.

**Comment by neheb** [comment]
Aside from the libmatroska problem, there's no other issue. Closing.

**Comment by neheb** [comment]
```
==33300==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x9399b7 in operator new(unsigned long) (/home/mangix/devstuff/gerbera/addr2/gerbera+0x9399b7)
    #1 0x7f07a43de621 in UpnpSendAdvertisementLowPower(int, int, int, int, int) /home/mangix/devstuff/npupnp/a/../src/api/upnpapi.cpp:1446:24
    #2 0x7f07a43de475 in UpnpSendAdvertisement(int, int) /home/mangix/devstuff/npupnp/a/../src/api/upnpapi.cpp:1400:41
    #3 0x7f07a43de4a4 in thread_autoadvertise(void*) /home/mangix/devstuff/npupnp/a/../src/api/upnpapi.cpp:1407:26
    #4 0x7f07a43e727d in void* std::__invoke_impl<void*, void* (*&)(void*), void*>(std::__invoke_other, void* (*&)(void*), void*&&) /usr/include/c++/11/bits/invoke.h:61:36
    #5 0x7f07a43e72ba in std::enable_if<is_invocable_r_v<void, void* (*&)(void*), void*>, void>::type std::__invoke_r<void, void* (*&)(void*), void*>(void* (*&)(void*), void*&&) /usr/include/c++/11/bits/invoke.h:111:28
    #6 0x7f07a43e55ba in std::_Function_handler<void (void*), void* (*)(void*)>::_M_invoke(std::_Any_data const&, void*&&) /usr/include/c++/11/bits/std_function.h:290:30
    #7 0xd5f00b in std::function<void (void*)>::operator()(void*) const /usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590:9
    #8 0x7f07a43f22aa in WorkerThread(void*) /home/mangix/devstuff/npupnp/a/../src/threadutil/ThreadPool.cpp:480:18
    #9 0x7f07a43f6385 in void* std::__invoke_impl<void*, void* (*)(void*), ThreadPool::Internal*>(std::__invoke_other, void* (*&&)(void*), ThreadPool::Internal*&&) /usr/include/c++/11/bits/invoke.h:61:36
    #10 0x7f07a43f6309 in std::__invoke_result<void* (*)(void*), ThreadPool::Internal*>::type std::__invoke<void* (*)(void*), ThreadPool::Internal*>(void* (*&&)(void*), ThreadPool::Internal*&&) /usr/include/c++/11/bits/invoke.h:96:40
    #11 0x7f07a43f627a in void* std::thread::_Invoker<std::tuple<void* (*)(void*), ThreadPool::Internal*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/include/c++/11/bits/std_thread.h:253:26
    #12 0x7f07a43f6235 in std::thread::_Invoker<std::tuple<void* (*)(void*), ThreadPool::Internal*> >::operator()() /usr/include/c++/11/bits/std_thread.h:260:20
    #13 0x7f07a43f6219 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void* (*)(void*), ThreadPool::Internal*> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211:20
    #14 0x7f07a41ed5c3  (/lib64/libstdc++.so.6+0xd95c3)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x901287 in malloc (/home/mangix/devstuff/gerbera/addr2/gerbera+0x901287)
    #1 0x7f07a43de602 in UpnpSendAdvertisementLowPower(int, int, int, int, int) /home/mangix/devstuff/npupnp/a/../src/api/upnpapi.cpp:1442:42
    #2 0x7f07a43de475 in UpnpSendAdvertisement(int, int) /home/mangix/devstuff/npupnp/a/../src/api/upnpapi.cpp:1400:41
    #3 0x7f07a43de4a4 in thread_autoadvertise(void*) /home/mangix/devstuff/npupnp/a/../src/api/upnpapi.cpp:1407:26
    #4 0x7f07a43e727d in void* std::__invoke_impl<void*, void* (*&)(void*), void*>(std::__invoke_other, void* (*&)(void*), void*&&) /usr/include/c++/11/bits/invoke.h:61:36
    #5 0x7f07a43e72ba in std::enable_if<is_invocable_r_v<void, void* (*&)(void*), void*>, void>::type std::__invoke_r<void, void* (*&)(void*), void*>(void* (*&)(void*), void*&&) /usr/include/c++/11/bits/invoke.h:111:28
    #6 0x7f07a43e55ba in std::_Function_handler<void (void*), void* (*)(void*)>::_M_invoke(std::_Any_data const&, void*&&) /usr/include/c++/11/bits/std_function.h:290:30
    #7 0xd5f00b in std::function<void (void*)>::operator()(void*) const /usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590:9
    #8 0x7f07a43f22aa in WorkerThread(void*) /home/mangix/devstuff/npupnp/a/../src/threadutil/ThreadPool.cpp:480:18
    #9 0x7f07a43f6385 in void* std::__invoke_impl<void*, void* (*)(void*), ThreadPool::Internal*>(std::__invoke_other, void* (*&&)(void*), ThreadPool::Internal*&&) /usr/include/c++/11/bits/invoke.h:61:36
    #10 0x7f07a43f6309 in std::__invoke_result<void* (*)(void*), ThreadPool::Internal*>::type std::__invoke<void* (*)(void*), ThreadPool::Internal*>(void* (*&&)(void*), ThreadPool::Internal*&&) /usr/include/c++/11/bits/invoke.h:96:40
    #11 0x7f07a43f627a in void* std::thread::_Invoker<std::tuple<void* (*)(void*), ThreadPool::Internal*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/include/c++/11/bits/std_thread.h:253:26
    #12 0x7f07a43f6235 in std::thread::_Invoker<std::tuple<void* (*)(void*), ThreadPool::Internal*> >::operator()() /usr/include/c++/11/bits/std_thread.h:260:20
    #13 0x7f07a43f6219 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void* (*)(void*), ThreadPool::Internal*> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211:20
    #14 0x7f07a41ed5c3  (/lib64/libstdc++.so.6+0xd95c3)

SUMMARY: AddressSanitizer: 20 byte(s) leaked in 2 allocation(s).
```

is the output with libnpupnp. @medoc92 believes it is no issue. I agree. 20 leaked bytes is not much.
