### ISSUE TITLE
Crashing while scaning media

### ISSUE THREAD

**Issue by fandangos** [gerbera/gerbera#2423]
I'm having a hard time getting a proper debug output to understand what is going on. 
I'm confident this is caused while scaning my media library.

I run Gerbera as a docker container on unraid. 

I'm trying to still run it as a docker but isolating it. 
From docker documentation to pass an argument when launching a container you need to give it with `-e` so meaning `-e --debug`

That's the only way I was able to launch it with --debug but still no debug output

here's the crash:
```
root@Tower:~# docker run --name='Gerbera5' --net='host' -e TZ="America/Sao_Paulo" -e --debug -e HOST_OS="Unraid" -e 'TCP_PORT_49494'='49494' -e 'UDP_PORT_1900'='1900' -v '/mnt/user/MUSIC/Hi-RES/':'/content':'ro' -v '/mnt/user/appdata/gerbera/config.xml':'/var/run/gerbera/config.xml':'rw' -v '/mnt/user/appdata/gerbera':'/var/run/gerbera':'rw' 'gerbera/gerbera'
2022-02-10 23:20:09   info: Gerbera UPnP Server 1.9.2 - http://gerbera.io/
2022-02-10 23:20:09   info: Copyright 2016-2021 Gerbera Contributors.
2022-02-10 23:20:09   info: Gerbera is free software, covered by the GNU General Public License version 2
2022-02-10 23:20:09   info: Loading configuration from: /var/run/gerbera/config.xml
2022-02-10 23:20:09   info: Checking configuration...
2022-02-10 23:20:09   info: Configuration check succeeded.
2022-02-10 23:20:09   info: Loading 0 configuration items from database
2022-02-10 23:20:10   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:20:10   info: Initialising UPnP with interface: <unset>, port: 49494
2022-02-10 23:20:10   info: IPv4: Server bound to: 192.168.0.198:49494
2022-02-10 23:20:10   info: IPv6: Server bound to: :49494
2022-02-10 23:20:10   info: IPv6 ULA/GLA: Server bound to: :49495
2022-02-10 23:20:10   info: The Web UI can be reached by following this link: http://192.168.0.198:49494/
2022-02-10 23:21:20   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:21:20   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:21:20   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:21:20   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:21:20   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:21:20   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:21:20   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:22:45   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:22:46   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:22:46   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:22:46   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:22:46   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:22:46   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-10 23:22:46   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
```

and here's the config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<config version="2" xmlns="http://mediatomb.cc/config/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mediatomb.cc/config/2 http://mediatomb.cc/config/2.xsd">
  <!--
     See http://gerbera.io or read the docs for more
     information on creating and using config.xml configuration files.
    -->
  <server>
    <ui enabled="yes" show-tooltips="yes">
      <accounts enabled="no" session-timeout="30">
        <account user="gerbera" password="gerbera" />
      </accounts>
    </ui>
    <name>Gerbera</name>
    <udn>uuid:1a1c10a6-6e2e-470d-a059-cb1198547ed0</udn>
    <home>/var/run/gerbera/</home>
    <webroot>/usr/local/share/gerbera/web</webroot>
    <!--
        How frequently (in seconds) to send ssdp:alive advertisements.
        Minimum alive value accepted is: 62

        The advertisement will be sent every (A/2)-30 seconds,
        and will have a cache-control max-age of A where A is
        the value configured here. Ex: A value of 62 will result
        in an SSDP advertisement being sent every second.
    -->
    <alive>1800</alive>
    <storage>
      <sqlite3 enabled="yes">
        <database-file>gerbera.db</database-file>
      </sqlite3>
      <mysql enabled="no">
        <host>localhost</host>
        <username>gerbera</username>
        <database>gerbera</database>
      </mysql>
    </storage>
    <containers enabled="yes">
      <container location="/LastAdded" title="Recently Added" sort="-last_updated">
        <filter>upnp:class derivedfrom "object.item" and last_updated &gt; "@last7"</filter>
      </container>
      <container location="/LastModified" title="Recently Modified" sort="-last_modified">
        <filter>upnp:class derivedfrom "object.item" and last_modified &gt; "@last7"</filter>
      </container>
    </containers>
    <extended-runtime-options>
      <ffmpegthumbnailer enabled="no">
        <thumbnail-size>128</thumbnail-size>
        <seek-percentage>5</seek-percentage>
        <filmstrip-overlay>yes</filmstrip-overlay>
        <workaround-bugs>no</workaround-bugs>
        <image-quality>8</image-quality>
      </ffmpegthumbnailer>
      <mark-played-items enabled="no" suppress-cds-updates="yes">
        <string mode="prepend">*</string>
        <mark>
          <content>video</content>
        </mark>
      </mark-played-items>
    </extended-runtime-options>
  </server>
  <import hidden-files="no">

    <autoscan use-inotify="yes">

    <directory location="/content" mode="inotify" 
    recursive="yes" hidden-files="no"/>

    </autoscan>
<resources case-sensitive="no">
    <fanart>
        <add-file name="cover.png"/>
		<add-file name="cover.jpg"/>
        <add-file name="folder.png"/>
		<add-file name="folder.jpg"/>
    </fanart>
    <resource>
        <add-file name="cover.png"/>
		<add-file name="cover.jpg"/>
        <add-file name="folder.png"/>
		<add-file name="folder.jpg"/>
    </resource>
</resources>
    <scripting script-charset="UTF-8">
      <common-script>/usr/local/share/gerbera/js/common.js</common-script>
      <playlist-script>/usr/local/share/gerbera/js/playlists.js</playlist-script>
      <virtual-layout type="builtin">
        <import-script>/usr/local/share/gerbera/js/import.js</import-script>
      </virtual-layout>
    </scripting>
    <mappings>
      <extension-mimetype ignore-unknown="no">
        <map from="asf" to="video/x-ms-asf" />
        <map from="asx" to="video/x-ms-asf" />
        <map from="dff" to="audio/x-dff" />
        <map from="dsf" to="audio/x-dsf" />
        <map from="flv" to="video/x-flv" />
        <map from="m2ts" to="video/mp2t" />
        <map from="m3u" to="audio/x-mpegurl" />
        <map from="m3u8" to="audio/x-mpegurl" />
        <map from="m4a" to="audio/mp4" />
        <map from="mka" to="audio/x-matroska" />
        <map from="mkv" to="video/x-matroska" />
        <map from="mp3" to="audio/mpeg" />
        <map from="mts" to="video/mp2t" />
        <map from="oga" to="audio/ogg" />
        <map from="ogg" to="audio/ogg" />
        <map from="ogm" to="video/ogg" />
        <map from="ogv" to="video/ogg" />
        <map from="ogx" to="application/ogg" />
        <map from="pls" to="audio/x-scpls" />
        <map from="ts" to="video/mp2t" />
        <map from="tsa" to="audio/mp2t" />
        <map from="tsv" to="video/mp2t" />
        <map from="wax" to="audio/x-ms-wax" />
        <map from="wm" to="video/x-ms-wm" />
        <map from="wma" to="audio/x-ms-wma" />
        <map from="wmv" to="video/x-ms-wmv" />
        <map from="wmx" to="video/x-ms-wmx" />
        <map from="wv" to="audio/x-wavpack" />
        <map from="wvx" to="video/x-ms-wvx" />
		<map from="wor" to="video/x-working" />
        <!-- Uncomment the line below for PS3 divx support -->
        <!-- <map from="avi" to="video/divx" /> -->
        <!-- Uncomment the line below for D-Link DSM / ZyXEL DMA-1000 -->
        <!-- <map from="avi" to="video/avi" /> -->
      </extension-mimetype>
      <mimetype-upnpclass>
        <map from="application/ogg" to="object.item.audioItem.musicTrack" />
        <map from="audio/*" to="object.item.audioItem.musicTrack" />
        <map from="image/*" to="object.item.imageItem" />
        <map from="video/*" to="object.item.videoItem" />
      </mimetype-upnpclass>
      <mimetype-contenttype>
        <treat mimetype="application/ogg" as="ogg" />
        <treat mimetype="audio/L16" as="pcm" />
        <treat mimetype="audio/flac" as="flac" />
        <treat mimetype="audio/mp4" as="mp4" />
        <treat mimetype="audio/mpeg" as="mp3" />
        <treat mimetype="audio/ogg" as="ogg" />
        <treat mimetype="audio/x-dsd" as="dsd" />
        <treat mimetype="audio/x-dsf" as="dsf" />
        <treat mimetype="audio/x-dff" as="dff" />		
        <treat mimetype="audio/x-flac" as="flac" />
        <treat mimetype="audio/x-matroska" as="mka" />
        <treat mimetype="audio/x-mpegurl" as="playlist" />
        <treat mimetype="audio/x-ms-wma" as="wma" />
        <treat mimetype="audio/x-scpls" as="playlist" />
        <treat mimetype="audio/x-wav" as="pcm" />
        <treat mimetype="audio/x-wavpack" as="wv" />
        <treat mimetype="image/jpeg" as="jpg" />
        <treat mimetype="video/mp4" as="mp4" />
        <treat mimetype="video/x-matroska" as="mkv" />
        <treat mimetype="video/x-msvideo" as="avi" />
      </mimetype-contenttype>
      <contenttype-dlnaprofile>
        <map from="avi" to="AVI" />
        <map from="mkv" to="MKV" />
        <map from="mp3" to="MP3" />
        <map from="mp4" to="AVC_MP4_EU" />
        <map from="mpeg" to="MPEG_PS_PAL" />
        <map from="pcm" to="LPCM" />
      </contenttype-dlnaprofile>
    </mappings>
    <online-content>
      <AppleTrailers enabled="no" refresh="43200" update-at-start="no" resolution="640" />
    </online-content>
  </import>
  <transcoding enabled="no">
    <mimetype-profile-mappings>
      <transcode mimetype="application/ogg" using="vlcmpeg" />
      <transcode mimetype="audio/ogg" using="ogg2mp3" />
      <transcode mimetype="video/x-flv" using="vlcmpeg" />
    </mimetype-profile-mappings>
    <profiles>
      <profile name="ogg2mp3" enabled="no" type="external">
        <mimetype>audio/mpeg</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>no</accept-ogg-theora>
        <agent command="ffmpeg" arguments="-y -i %in -f mp3 %out" />
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>
      <profile name="vlcmpeg" enabled="no" type="external">
        <mimetype>video/mpeg</mimetype>
        <accept-url>yes</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <agent command="vlc" arguments="-I dummy %in --sout #transcode{venc=ffmpeg,vcodec=mp2v,vb=4096,fps=25,aenc=ffmpeg,acodec=mpga,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=ps,dst=%out} vlc:quit" />
        <buffer size="14400000" chunk-size="512000" fill-size="120000" />
      </profile>
    </profiles>
  </transcoding>
</config>

```

maybe it has something to do with folder.jpg? and cover.jpg?

**Comment by KarlStraussberger** [comment]
Looks like an old friend to me. Can you try running current head version `gerbera/gerbera:sha-a89ec1b`

**Comment by fandangos** [comment]
I'm testing it but I can't access the webui. 

```
root@Tower:~# docker run --name='Gerbera7' --net='host' -e TZ="America/Sao_Paulo" -e "--debug" -e HOST_OS="Unraid" -e 'TCP_PORT_49494'='49494' -e 'UDP_PORT_1
900'='1900' -v '/mnt/user/MUSIC/Hi-RES/':'/content':'ro' -v '/mnt/user/appdata/gerbera/config.xml':'/var/run/gerbera/config.xml':'rw' -v '/mnt/user/appdata/g
erbera':'/var/run/gerbera':'rw' 'gerbera/gerbera:sha-a89ec1b'
Unable to find image 'gerbera/gerbera:sha-a89ec1b' locally
sha-a89ec1b: Pulling from gerbera/gerbera
59bf1c3509f3: Already exists
d30abd40980e: Already exists
71e6758a4084: Already exists
3f446fc1a2e6: Pull complete
7c92761d00bd: Pull complete
ac08b619c4ea: Pull complete
e14705b1da66: Pull complete
1e0443f362c7: Pull complete
aaea1409a306: Pull complete
Digest: sha256:eabda9b80d0bc45e5b698c64e0eb5ecb7eeff85fae419cfbf61e341084a6a3dd
Status: Downloaded newer image for gerbera/gerbera:sha-a89ec1b
2022-02-11 08:15:29   info: Gerbera UPnP Server v1.9.2-339-ga89ec1b2 - http://gerbera.io/
2022-02-11 08:15:29   info: Copyright 2016-2021 Gerbera Contributors.
2022-02-11 08:15:29   info: Gerbera is free software, covered by the GNU General Public License version 2
2022-02-11 08:15:29   info: Loading configuration from: /var/run/gerbera/config.xml
2022-02-11 08:15:29   info: Checking configuration...
2022-02-11 08:15:29   info: Configuration check succeeded.
2022-02-11 08:15:29   info: Running an automatic database upgrade from database version 14 to version 15...
2022-02-11 08:15:35   info: Database upgrade to version 15 successful.
2022-02-11 08:15:35   info: Loading 0 configuration items from database
2022-02-11 08:15:35   info: Loading autoscan location: /content; recursive: true, last_modified: 2022-02-10 09:34:15
2022-02-11 08:15:35   info: Initialising UPnP with interface: <unset>, port: 49494
2022-02-11 08:15:35   info: IPv4: Server bound to: 192.168.0.198:49494
2022-02-11 08:15:35   info: IPv6: Server bound to: :49494
2022-02-11 08:15:35   info: IPv6 ULA/GLA: Server bound to: :49495
2022-02-11 08:15:35   info: Will send UPnP Alive advertisements every 870 seconds
2022-02-11 08:15:35   info: The Web UI can be reached by following this link: http://192.168.0.198:49494
2022-02-11 08:16:03 warning: Web Error: 400 no session id given
2022-02-11 08:16:03 warning: Web Error: 400 no session id given
2022-02-11 08:16:09 warning: Web Error: 400 no session id given
2022-02-11 08:16:13 warning: Web Error: 400 no session id given
2022-02-11 08:16:15 warning: Web Error: 400 no session id given
2022-02-11 08:16:17 warning: Web Error: 400 no session id given
2022-02-11 08:16:18 warning: Web Error: 400 no session id given
2022-02-11 08:16:18 warning: Web Error: 400 no session id given
2022-02-11 08:16:18 warning: Web Error: 400 no session id given
```

Do I need to rebuild the html file?
This happened when I tried any other docker image that's not `gerbera/gerbera`

Anything to do with?
```
    </ui>
    <name>Gerbera</name>
    <udn>uuid:1a1c10a6-6e2e-470d-a059-cb1198547ed0</udn>
    <home>/var/run/gerbera/</home>
    <webroot>/usr/local/share/gerbera/web</webroot>
    <!--
```

**Comment by KarlStraussberger** [comment]
This looks good. The `Web Error` happens because you did not reload the browser's page.

**Comment by fandangos** [comment]
Newer version just crash and I can't get any output. Just exist while scanning. 

`-e --debug` doesn't change anything. 
I'm trying to make the config.xml simpler to check if this makes any difference and I'm rebuilding the database from scratch with `gerbera:latest`

**Comment by fandangos** [comment]
After a ton of trial and error I finally found what causes the crash.

[1994] The Division Bell (2014, 0825646293285, EU) DSD
It's the DSD128 vinyl rip of The Division Bell. 

```
Number of tracks:  11
Official DR value: DR11

Samplerate:        5644800 Hz / PCM Samplerate: 176400 Hz
Channels:          2
Bits per sample:   1
Bitrate:           11290 kbps
Codec:             DSD128
================================================================================
```

So that makes sense that it's outputing `throwing an instance of 'std::out_of_range'`

I have to test with @whyman fix on my VM. 
Maybe this fixed the sample rate output AND crashing with DSD128

**Comment by fandangos** [comment]
Yeap @whyman fix the crash with DSD128 and probably with DSD256 and DSD512

<a href="https://ibb.co/7V7Jhsg"><img src="https://i.ibb.co/k0YgZN3/dsdfix3.jpg" alt="dsdfix3" border="0"></a>

Any chance you can aprove his PR so we can have this on docker hub? Please? :))

**Comment by neheb** [comment]
I ran a backtrace:

```
#0  0x00007ffff5f46ce8 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /lib64/libstdc++.so.6
#1  0x000000000058ee7a in CdsItem::getMimeType[abi:cxx11]() const ()
#2  0x0000000000579367 in ContentManager::createSingleItem(std::filesystem::__cxx11::directory_entry const&, std::filesystem::__cxx11::path const&, bool, bool, bool, bool, std::shared_ptr<CMAddFileTask> const&) ()
#3  0x0000000000579ad0 in ContentManager::_addFile(std::filesystem::__cxx11::directory_entry const&, std::filesystem::__cxx11::path, AutoScanSetting&, std::shared_ptr<CMAddFileTask> const&) ()
#4  0x000000000058301c in ContentManager::addFileInternal(std::filesystem::__cxx11::directory_entry const&, std::filesystem::__cxx11::path const&, AutoScanSetting&, bool, bool, unsigned int, bool) ()
#5  0x00000000005808c0 in ContentManager::_rescanDirectory(std::shared_ptr<AutoscanDirectory> const&, int, std::shared_ptr<GenericTask> const&) ()
#6  0x000000000058b03a in CMRescanDirectoryTask::run() ()
#7  0x000000000058703f in ContentManager::threadProc() ()
#8  0x000000000058b9f1 in ContentManager::run()::$_0::operator()(void*) const ()
#9  0x000000000058b9b2 in void* std::__invoke_impl<void*, ContentManager::run()::$_0&, void*>(std::__invoke_other, ContentManager::run()::$_0&, void*&&) ()
#10 0x000000000058b942 in std::enable_if<is_invocable_r_v<void, ContentManager::run()::$_0&, void*>, void>::type std::__invoke_r<void, ContentManager::run()::$_0&, void*>(ContentManager::run()::$_0&, void*&&) ()
#11 0x000000000058b832 in std::_Function_handler<void (void*), ContentManager::run()::$_0>::_M_invoke(std::_Any_data const&, void*&&) ()
#12 0x000000000059ed85 in std::function<void (void*)>::operator()(void*) const ()
#13 0x000000000059ed23 in ThreadRunner<std::_V2::condition_variable_any, std::recursive_mutex>::startThread()::{lambda(void*)#1}::operator()(void*) const ()
#14 0x000000000059ece5 in ThreadRunner<std::_V2::condition_variable_any, std::recursive_mutex>::startThread()::{lambda(void*)#1}::__invoke(void*) ()
#15 0x00007ffff5c67b1a in start_thread () at /lib64/libc.so.6
#16 0x00007ffff5cec650 in clone3 () at /lib64/libc.so.6
```

This is on master.
