### ISSUE TITLE
infinite loop importing playlist

### ISSUE THREAD

**Issue by hmoffatt** [gerbera/gerbera#2489]
Gerbera seems to be stuck in an infinite loop importing a particular directory including a playlist. It's using 100% of CPU and never progresses any further on the import. I've reproduced this on amd64 and on arm.

The playlist is simply

```
[playlist]
NumberOfEntries=9
Version=2
File1=01-The Power of Rome and the Christian Heart.ogg
File2=02-Chirdren's March.ogg
File3=03-Bell Piece.ogg
File4=04-Blithe Bells.ogg
File5=05-The Immovable Do.ogg
File6=06-Hill Song I.ogg
File7=07-Hill Song II.ogg
File8=08-Irish Tune from County Derry.ogg
File9=09-Marching Song of Democracy.ogg
```

and the file list is

```
'01-The Power of Rome and the Christian Heart.ogg'
"02-Chirdren's March.ogg"
'03-Bell Piece.ogg'
'04-Blithe Bells.ogg'
'05-The Immovable Do.ogg'
'06-Hill Song I.ogg'
'07-Hill Song II.ogg'
'08-Irish Tune from County Derry.ogg'
'09-Marching Song of Democracy.ogg'
'EDITION 8_ Works for Wind Orchestra 2.pls'
```

(quotes added around the filenames by ls)

**Comment by hmoffatt** [comment]
I opened gdb and had a look at what all the threads are doing and I see

```
#0  0x00007ff0c17d3981 in ?? () from /usr/lib/libduktape.so.206
#1  0x00007ff0c17c5e5c in ?? () from /usr/lib/libduktape.so.206
#2  0x00007ff0c17c69f4 in ?? () from /usr/lib/libduktape.so.206
#3  0x00007ff0c17c9ed5 in duk_get_prop () from /usr/lib/libduktape.so.206
#4  0x00007ff0c17e083e in ?? () from /usr/lib/libduktape.so.206
#5  0x00007ff0c17c5e5c in ?? () from /usr/lib/libduktape.so.206
#6  0x00007ff0c17c0286 in ?? () from /usr/lib/libduktape.so.206
#7  0x00007ff0c17c4eb6 in ?? () from /usr/lib/libduktape.so.206
#8  0x00007ff0c17c5e41 in ?? () from /usr/lib/libduktape.so.206
#9  0x00007ff0c17d1039 in ?? () from /usr/lib/libduktape.so.206
#10 0x00007ff0c17c743f in ?? () from /usr/lib/libduktape.so.206
#11 0x00007ff0c17cad81 in duk_pcall () from /usr/lib/libduktape.so.206
#12 0x00005638b641d83e in Script::_execute () at /gerbera_build/src/content/scripting/script.cc:399
#13 0x00005638b641db2f in Script::execute () at /gerbera_build/src/content/scripting/script.cc:436
#14 0x00005638b641780d in PlaylistParserScript::processPlaylistObject () at /gerbera_build/src/content/scripting/playlist_parser_script.cc:239
#15 0x00005638b63ed0bd in ContentManager::createSingleItem () at /gerbera_build/src/content/content_manager.cc:420
#16 0x00005638b63ed716 in ContentManager::addRecursive () at /gerbera_build/src/content/content_manager.cc:855
#17 0x00005638b63efdfe in ContentManager::_addFile () at /gerbera_build/src/content/content_manager.cc:452
#18 0x00005638b63f0007 in CMAddFileTask::run () at /gerbera_build/src/content/content_manager.cc:1794
#19 0x00005638b63f6760 in ContentManager::threadProc () at /gerbera_build/src/content/content_manager.cc:1347
#20 0x00005638b63f98fc in std::function<void (void*)>::operator()(void*) const () at /usr/include/c++/10.3.1/bits/std_function.h:622
#21 ThreadRunner<std::_V2::condition_variable_any, std::recursive_mutex>::startThread()::{lambda(void*)#1}::operator()(void*) const () at /gerbera_build/src/util/thread_runner.h:198
#22 ThreadRunner<std::_V2::condition_variable_any, std::recursive_mutex>::startThread()::{lambda(void*)#1}::_FUN(void*) () at /gerbera_build/src/util/thread_runner.h:196
#23 0x00007ff0c1a48221 in ?? () from /lib/ld-musl-x86_64.so.1
#24 0x0000000000000000 in ?? ()
```

I am using the js import, but I have not customised anything to do with playlists.

I removed that pls and it locked up on another, which also had filenames containing apostrophes FWIW.

**Comment by KarlStraussberger** [comment]
Because of #2463, I assume you're running latest.

**Comment by hmoffatt** [comment]
I'm a few commits behind - 7bb7422d. I'll try the latest.

**Comment by KarlStraussberger** [comment]
You may wait a little longer. The issue is the end of the file or the handling of empty lines which is not detected correctly. PR to follow.

**Comment by hmoffatt** [comment]
Thanks working well now.
